#ifndef TOS_NET_CFG_H__
#define TOS_NET_CFG_H__

#define PKTBUF_BLK_SIZE 1024
#define PKTBUF_BLK_CNT 256
#define PKTBUF_BUF_CNT 128
#define NET_ENDIAN_LITTLE 1

#define NETIF_HWADDR_SIZE 10
#define NETIF_NAME_SIZE 16
#define NETIF_DEV_CNT 4
#define NETIF_INQ_SIZE 16
#define NETIF_OUTQ_SIZE 16
#define ARP_CACHE_SIZE 8
#define ARP_MAX_PKT_WAIT 8

#endif
