#ifndef TOS_NET_PROTOCOL_H
#define TOS_NET_PROTOCOL_H

#define NET_PROTOCOL_ARP 0x0806
#define NET_PROTOCOL_IPV4 0x0800
#define NET_PROTOCOL_ICMPV4 0x01
#define NET_PROTOCOL_UDP 0x11
#define NET_PROTOCOL_TCP 0x06

#endif
