#!/usr/bin/env bash
set -eu

root=${QS_ROOT:-$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)}
export QS_ROOT=$root
if [ -z "${QS_STAGE:-}" ]; then
  QS_STAGE=m6b
fi
export QS_STAGE
if [ "${QS_M6C2_STRESS:-0}" = 1 ]; then
  export QS_KERNEL_CPPFLAGS="-DQS_M2C_TEST -DQS_M3_TEST -DQS_M4_TEST -DQS_M5_TEST -DQS_M6A_TEST -DQS_M6B_TEST -DQS_ALLOC_ITERATIONS=50000 -DQS_MIGRATION_TARGET=10000 -DQS_STRESS_MIN_TICKS=1200000000ULL -DQS_FATFS_ITERATIONS=4 -DQS_NET_ITERATIONS=32 -DQS_NET_RESETS=1"
else
  export QS_KERNEL_CPPFLAGS="-DQS_M2C_TEST -DQS_M3_TEST -DQS_M4_TEST -DQS_M5_TEST -DQS_M6A_TEST -DQS_M6B_TEST -DQS_ALLOC_ITERATIONS=10000 -DQS_MIGRATION_TARGET=100 -DQS_FATFS_ITERATIONS=4 -DQS_NET_ITERATIONS=32 -DQS_NET_RESETS=1"
fi
if [ "${QS_M6C1_TEST:-0}" = 1 ]; then
  export QS_KERNEL_CPPFLAGS="$QS_KERNEL_CPPFLAGS -DQS_M6C1_TEST"
fi
if [ "${QS_M6C2_TEST:-0}" = 1 ]; then
  export QS_KERNEL_CPPFLAGS="$QS_KERNEL_CPPFLAGS -DQS_M6C2_TEST"
fi
if [ "${QS_M6C2_STRESS:-0}" = 1 ]; then
  export QS_KERNEL_CPPFLAGS="$QS_KERNEL_CPPFLAGS -DQS_M6C2_STRESS"
fi
if [ "${QS_M7A_TEST:-0}" = 1 ]; then
  export QS_KERNEL_CPPFLAGS="$QS_KERNEL_CPPFLAGS -DQS_M7A_TEST"
fi
if [ "${QS_M7B_TEST:-0}" = 1 ]; then
  export QS_KERNEL_CPPFLAGS="$QS_KERNEL_CPPFLAGS -DQS_M7B_TEST"
fi
exec "$root/scripts/m6a-build.sh"
